[package]
name = "wloop_flatc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.1.2"

[lib]
name = "wloop_flatc"
path = "lib.rs"
